# Generated by Django 3.1.1 on 2020-09-06 14:27

import django.core.files.storage
from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20200903_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/my_sell/', location='D:\\untitled4\\media/my_sell/'), upload_to=menu.models.image_directory_path),
        ),
    ]
